services:
  source_postgres:
    image: postgres:latest
    ports:
      - "5433:5432"
    networks:
      - etl_network
    environment:
      POSTGRES_DB: source_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - ./source_db_init/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  destination_postgres:
    image: postgres:latest
    ports:
      - "5434:5432"
    networks:
      - etl_network
    environment:
      POSTGRES_DB: destination_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
  
  etl_script:
    build:
      context: ./etl
      dockerfile: Dockerfile
    command: ["python", "etl_script.py"]
    networks:
      - etl_network
    depends_on:
      - source_postgres
      - destination_postgres

  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:1.4.7
    command:
      [
        "run",
        "--profiles-dir",
        "/root",
        "--project-dir",
        "/dbt"
      ]
    networks: 
      - etl_network
    volumes:
      - ./custom_postgres:/dbt
      - ~/.dbt:/root
    depends_on:
      - etl_script
    environment:
      DBT_PROFILE: default
      DBT_TARGET: dev

networks:
  etl_network:
    driver: bridge
